# -*- coding: utf-8 -*-
"""Ai advanced course 2 python string all practice.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1czQPuog53NFMjgNMuteb-9Bb_pSzWKB-

# **String**
"""

Ai=("Ai is a magic to solve problems quiqly ")
print(Ai)

integer=("1" "2" "3" "4" "5" "6" "7" "8" "9")
string1="1235"
string2="1659"
string3="-5"
string4="0.5"
string5=("go back123")
print(string1.isdigit())
print(string3.isnumeric())
print(string4.isdecimal())
print(string2.isdecimal())
print(string5.isnumeric())
print(type(string5))

user_number="1234kjg"
if user_number.isnumeric():
  print(" number is numeric")
else:
  print("number is not numeric")

"""Write a function to check if a given string contains only numeric characters.




"""

user_number=input("enter value:")
number = str(user_number)
if number.isnumeric():
  print("yes value is numeric")
else:
  print("value is not numeric")

"""Given a string representing a number, convert it to an actual integer or float.


"""

number_string="12487654"
integer=int(number_string)
floating=float(number_string)
print(number_string)
print(type(number_string))
print(type(integer))
print(floating)
print(type(floating))



"""Identify the largest and smallest numbers within a string containing multiple numbers separated by commas or spaces.

"""

number_ofstring="34" " " "222" " " "31" " " "1"
number_ofstring1="3652" " " "78"
number_ofstring2="45" " " "65" " " "77" " " "45"
number_ofstring3="its night one am"
print(max(number_ofstring,number_ofstring1,number_ofstring2))
print(min(number_ofstring,number_ofstring1,number_ofstring2))
print(number_ofstring3.isnumeric())



"""concatenate  all the numbers in a string of mixed characters and digits.

"""

mixed_string="Ai advanced model take time to trian"
mixed_string1="2021"
mixed_string2="revolutionalize year for Ai"
concatenation_ofstring = mixed_string  +" "+  mixed_string1  +" "+  mixed_string2
print(concatenation_ofstring)



"""Extract all occurrences of a specific digit from a numeric string.

"""

import re
numeric_string="166793846789305411235"
target_digit='6'
print("f re.findall'[target_digit]':[numeric_string]")



"""Implement a function to perform basic arithmetic operations (addition, subtraction, multiplication, etc.) on two numeric strings."""

numeric_string1="12356"
numeric_string2="22349876"
add=int(numeric_string1 + numeric_string2)
sub=int(numeric_string1) - int(numeric_string2)
multiplication=int(numeric_string1) *  int(numeric_string2)
print(add)
print(sub)
print(multiplication)

string="hello" *4
print(string)



"""Given a string representing a mathematical expression (e.g., "2 + 3 * 4"), evaluate the expression and return the result as a string or number.

"""

